#poetry run python generateValidationFiles_SC_I1.py
#poetry run python generateValidationFiles_SC_I2.py
#poetry run python generateValidationFiles_AT_I1.py
#poetry run python generateValidationFiles_AT_I2.py
#poetry run python generateValidationFiles_CC_I1.py
#poetry run python generateValidationFiles_CC_I2.py
#poetry run python generateValidationFiles_NN1x_I1.py
#poetry run python generateValidationFiles_NN1x_I2.py
poetry run python generateValidationFiles_NNx_I1.py
poetry run python generateValidationFiles_NNx_I2.py
#poetry run python generateValidationFiles_AFC2x_I2.py
#poetry run python generateValidationFiles_AFC33_I2.py